influxdb {
  server-url      = "http://localhost:8086"
  org-name        = "homedata"
  project-bucket  = "home_data"
  time-resolution = 15 minutes
  batch-writes    = 250
}

octopus {
  requests-per-sec = 1
}

tado {
  requests-per-sec = 3
}
