influxdb {
  server-url      = "http://localhost:8086"
  org-name        = "homedata"
  project-bucket  = "home_data"
  time-resolution = 15 minutes
  batch-writes    = 250
}

octopus {
  requests-per-sec = 2
  page-size        = 100
}

tado {
  requests-per-sec = 6
}

scrape-log {
  log-path   = ~/.homedata/scrape.log
  batch-size = 10
  batch-wait = 50 milliseconds
}
