homedata {
  poll-time = 15 minutes
  scrape-from-date = "2024-01-22T15:46:39Z"

  scrape-log {
    log-path   = ~/.homedata/scrape.log
    batch-size = 100
    batch-wait = 250 milliseconds
  }

  influxdb {
    server-url      = "http://localhost:8086"
    org-name        = "homedata"
    project-bucket  = "home_data"
    time-resolution = 15 minutes
    batch-writes    = 250
    auth-token      = ${?HOMEDATA_INFLUXDB_AUTH_TOKEN}
  }

  octopus {
    requests-per-sec   = 4
    page-size          = 100
    api-key            = ${?HOMEDATA_OCTOPUS_API_KEY}
    account-number     = ${?HOMEDATA_OCTOPUS_ACCOUNT_NUMBER}
    electricity-mpan   = ${?HOMEDATA_OCTOPUS_ELECTRICITY_MPAN}
    electricity-serial = ${?HOMEDATA_OCTOPUS_ELECTRICITY_SERIAL}
    gas-mprn           = ${?HOMEDATA_OCTOPUS_GAS_MPRN}
    gas-serial         = ${?HOMEDATA_OCTOPUS_GAS_SERIAL}
  }

  tado {
    requests-per-sec = 12
    initial-refresh-token {
      token      = ${?HOMEDATA_TADO_TOKEN}
      issue-time = ${?HOMEDATA_TADO_TOKEN_ISSUE_TIME}
    }
  }
}
