services:

  homedata:
    image: colofabrix/homedata:1.0.0
    container_name: homedata
    restart: unless-stopped
    volumes:
      - ./config/homedata/application.conf:/opt/homedata/config/application.conf:ro
      - ./data/homedata:/opt/homedata/data
    env_file:
      - secrets.env
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g -Dconfig.file=/opt/homedata/config/application.conf -Dcats.effect.warnOnNonMainThreadDetected=false
      # - HOMEDATA_INFLUXDB_AUTH_TOKEN="..."
      # - HOMEDATA_OCTOPUS_API_KEY="..."
      # - HOMEDATA_OCTOPUS_ACCOUNT_NUMBER="..."
      # - HOMEDATA_OCTOPUS_ELECTRICITY_MPAN="..."
      # - HOMEDATA_OCTOPUS_ELECTRICITY_SERIAL="..."
      # - HOMEDATA_OCTOPUS_GAS_MPRN="..."
      # - HOMEDATA_OCTOPUS_GAS_SERIAL="..."
      # - HOMEDATA_TADO_TOKEN="..."
      # - HOMEDATA_TADO_TOKEN_ISSUE_TIME="..."
      # - TADO4S_CLIENT_ID="..."

  influxdb:
    container_name: influxdb
    image: influxdb:2.7.4
    restart: 'no'
    ports:
      - "8086:8086"
    volumes:
      - ./config/influxdb:/etc/influxdb2
      - ./data/influxdb:/var/lib/influxdb2
    env_file:
      - secrets.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE="setup"
      - DOCKER_INFLUXDB_INIT_ORG="com.colofabrix"
      - DOCKER_INFLUXDB_INIT_BUCKET="mainbucket"
      - DOCKER_INFLUXDB_INIT_RETENTION="1w"
      # - DOCKER_INFLUXDB_INIT_USERNAME="..."
      # - DOCKER_INFLUXDB_INIT_PASSWORD="..."
      # - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN="..."

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.2.3
    restart: 'no'
    ports:
      - '3000:3000'
    volumes:
      - ./config/grafana:/etc/grafana:ro
      - ./data/grafana:/var/lib/grafana
    env_file:
      - secrets.env
