influxdb {
  server-uri      = "http://127.0.0.1:8086"
  octopus-bucket  = "octopus"
  organization-id = "dd87acad77d7e016"
  auth-token      = "VRB6CbkkF4CcAG8dKHu56D_t8kA4IumEMI5-QazdKz0ry3vArEe3tOCSw3YvgTnHinIEicUXpEC-5rI3Zu1rjQ=="
}

octopus {
  base-url = "https://api.octopus.energy/"

  # Sensitive configuration
  #account-number     = ""
  #api-key            = ""
  #electricity-mpan   = ""
  #electricity-serial = ""
  #gas-mprn           = ""
  #gas-serial         = ""
}

tado {
  # Sensitive configuration
  #username = ""
  #password = ""
}
