homedata {
  poll-time = 60 minutes
  scrape-from-date = "2025-11-23T00:00:00Z"

  scrape-log {
    log-path   = /opt/homedata/data/scrape.log
    batch-size = 100
    batch-wait = 250 milliseconds
  }

  influxdb {
    server-url   = "http://influxdb:8086"
    batch-writes = 250
  }

  octopus {
    requests-per-sec = 4
    page-size        = 100
  }

  tado {
    requests-per-sec = 12
  }
}

tado4s {
  ignore-ssl = true
  token-path = /opt/homedata/data/tado4s-token.conf
}

timeflux {
  ignore-ssl = true
}

cuttlefish {
  ignore-ssl = true
}
